# This is a basic workflow to help you get started with Actions

name: Firely Validation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, QA, integration ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Validate all conformance resources using Firely Terminal 
  CI_FHIR_VALIDATION:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Install .NET runtime
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      
      # Install Java runtime (only needed if you want to run the offical HL7 Java validator)
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
        
#      - name: Firely.Terminal validation
#        uses: FirelyTeam/firely-terminal-pipeline@v0.3.2
#        with:
#          PATH_TO_CONFORMANCE_RESOURCES: resources terminology
#          PATH_TO_EXAMPLES: examples
#          PATH_TO_QUALITY_CONTROL_RULES: qa-validate-all
#          OUTPUT_FORMAT: SUMMARY
#          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
#          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}

      - name: Gather files to validate
        run: |
           chmod +x ./.github/scripts/GetValidationFiles.sh
           .github/scripts/GetValidationFiles.sh

      - name: Java validation of resources and terminology
        uses: FirelyTeam/firely-terminal-pipeline@v0.3.2
        with:
          PATH_TO_CONFORMANCE_RESOURCES: ValidationFiles
          PATH_TO_QUALITY_CONTROL_RULES: qa-validate-all
          DOTNET_VALIDATION_ENABLED: FALSE
          JAVA_VALIDATION_ENABLED: TRUE
          JAVA_VALIDATION_OPTIONS: -html-output ./validation-output-resources.html
          OUTPUT_FORMAT: RAW
          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}

#      - name: Java validation of examples
#        uses: FirelyTeam/firely-terminal-pipeline@v0.3.2
#        with:
#          PATH_TO_CONFORMANCE_RESOURCES: ValidationFiles
#          PATH_TO_EXAMPLES: ValidationFiles
#          PATH_TO_QUALITY_CONTROL_RULES: qa-validate-examples
#          DOTNET_VALIDATION_ENABLED: FALSE
#          JAVA_VALIDATION_ENABLED: TRUE
#          JAVA_VALIDATION_OPTIONS: -html-output ./validation-output-examples.html
#          OUTPUT_FORMAT: RAW
#          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
#          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}

      - name: Create validation results file
        uses: actions/upload-artifact@v3
        with:
          name: FHIR-validation-results
          path: ./validation-output-resources.html         